sudo: required
services:
    - docker

before_install:
    - docker build -t shanequ/docker-react  -f Dockerfile.dev .

# -e: set up environment variable:
#     CI=true: indicate running in CI mode
# --coverage to show test coverage
script:
    - docker run -e CI=true shanequ/docker-react npm run test

deploy:
    edge: true
    provider: elasticbeanstalk
    region: "ap-southeast-2"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-ap-southeast-2-676457011483"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY